# fly.toml app configuration file generated for panificador on 2026-07-30T11:10:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'panificador'
primary_region = 'cdg'

[build]

[env]
  ASPNETCORE_URLS = 'http://0.0.0.0:8080'
  ConnectionStrings__Default = 'Data Source=/data/todo.db'
  TZ = 'Europe/Madrid'

[[mounts]]
  source = 'panificador_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
